config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" } do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  root to: "welcomes#index"
  resources :categories
  resources :exercises
  resources :workouts
  resources :friendships
  resources :workout_exercise_connectors
  
  resources :users do
     resources :workout_sessions
     resources :stats
     resources :goals
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :stat
  has_one :goal
  has_many :workout_sessions
  has_many :workouts, through: :workout_sessions
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user


  validates :name, :role, presence: true
  validates :email, :role, presence: true

  mount_uploader :image, ProfilePhotoUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name  
      user.image = auth.info.image 
    end
  end 

  def largeimage
    "http://graph.facebook.com/#{self.uid}/picture?type=large"
  end
 
  def normalimage
    "http://graph.facebook.com/#{self.uid}/picture?"
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login

  def index
    @users = User.where.not(id: current_user.id)
  end

  def show
    @user = User.find(params[:id])
    @user_workout_sessions = @user.workout_sessions
    @user_stats = @user.stat
    @user_goals = @user.goal
    @user_friends = @user.friends
  end

  def create
    @user = User.create(user_params)
  end

  def update
    @user = User.find(params[:id])
    @user.assign_attributes(user_params)
    if @user.save
      flash[:notice] = "Updated profile!"
      redirect_to user_path(@user)
    else
      flash[:notice] = "Oops, something went wrong. Please try again!"
      render :edit
    end
  end

  def edit
    @user = current_user
  end

  def destroy
    @user = (current_user)
    @user_workout_session = @user.workout_sessions[0]
    @user_workout_session.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:image, :profile_photo, :name, :age, :gender, :location, :occupation, :gym, :about)
  end

   def require_login
    unless current_user
      redirect_to new_user_registration_path
    end
  end
end

app/views/users/edit.html.erb
<div class = 'panel margin-top opacity'>
  <h3>Edit Personal Info </h3>

  <%= simple_form_for @user do |f| %>
    <%= f.input :age %>
    <%= f.input :location %>
    <%= f.input :occupation %>
    <%= f.input :gym %>
    <%= f.input :about %>
    <%= f.input :gender, as: :radio_buttons, collection:['Male', 'Female']%>
    <%= "Update Profile Picture" %>
    <%= f.file_field :profile_photo %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class = 'panel opacity margin-top'>
  <div class = 'row'>
    <div class="large-6 columns">
      <h4>Users</h4>
        <ul>
          <% @users.each do |user|%>
           <% if user.image.blank? %>
            <li><%= image_tag("https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/256/dumbbell.png", size: "100x100") %><br>
            <%= link_to user.name, user_path(user)%>
            <%= button_to "Add Friend", friendships_path(friend_id: user), method: :post 
            %>
            <br>
          <%else%>
            <li><%= image_tag user.image_url(:thumb).to_s %>
            <%= link_to "#{user.name}", user_path(user) %><br>
            <%= button_to "Add Friend", friendships_path(friend_id: user), method: :post %></li><br>
          <%end%>
        <%end%>
        </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class = "panel overflow opacity margin-top">
  <div class="profile-container">
    <div class="pic">
      <h2><%= "#{ @user.name }" %></h2><br>
      <%= image_tag(@user.largeimage)%>
      <br>
    </div>
  </div>

  <div class="about-container">
    <h2 id = 'about'>About</h2>
    <% if @user.age == nil %>
       <%= "Age: --" %>
       <br>

    <% else %>
      <%= "Age: #{@user.age}" %>
     <br>
    <% end %>
    <br>

    <% if @user.location == nil %>
      <%= "Location: --" %>
    <% else %>
      <%= "Location: #{@user.location}" %>
     <br>
    <% end %>
    <br>

    <% if @user.gender == nil %>
      <%= "Gender: --" %>
    <% elsif @user.gender == false %>
      <%= "Gender: Male" %>
    <% else %>
      <%= "Gender: Female"%>
     <br>
    <%end%>
    <br>

    <% if @user.occupation == nil %>
      <%= "Occupation: --" %>
    <% else %>
      <%= "Occupation: #{@user.occupation}" %>
     <br>
    <% end %>
    <br>

    <% if @user.gym == nil %>
      <%= "Gym: --" %>
    <% else %>
      <%= "Current Gym: #{@user.gym}" %>
     <br>
    <% end %>
    <br>

    <% if @user.about == nil %>
      <%= "About: --" %>
    <% else %>
      <%= " Personal Description: #{@user.about}" %>
     <br>
    <%end%>
    <br>

    <% if @user != current_user %>
      <%= ''%>
    <%else%>
      <%= link_to "Edit Profile", edit_user_path(@user), :class => 'myButton' %><br><br>
     <br>
    <%end%>
   </div>
</div>

<div class = "panel opacity">
  <% if @user_friends.count == 0  %>
    <%= ' No Current Friends' %><br>
    <%= link_to ' Find Friends', users_path%><br><br>
  <% else %>
    <h4>Friends</h4>
      <ul class="small-block-grid-3 no-bullet">
        <% @user.friends.each do |user| %> 
          <li>
            <%= image_tag("https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/256/dumbbell.png", size: "100x100") %>
            <%= user.name %><br>
            <%= link_to "Remove Friend", friendship_path, method: :delete, :class => 'myButton' %>
          </li>
         <% end %>
      </ul>
  <% end %>
</div>  

<div class = "panel opacity">
  <div class ='row'>
    <div class="large-6 columns">
      <%if @user_stats != nil%>
        <h4>Current Stats</h4>
          <%= "Bench Max: #{ @user_stats.bench }" %><br>
          <%= "Squat Max: #{ @user_stats.squat }" %><br>
          <%= "Dead lift Max: #{ @user_stats.dead_lift }" %><br>
          <%= "Best Mile time: #{ @user_stats.mile} " %><br>
          <% if @user != current_user %>
            <%= ''%>
          <% else %>
            <%= link_to "Edit your current stats", edit_user_stat_path(@user, @user.stat), :class => 'myButton' %><br>
          <br>
          <%end%>
      <%else%>
        <%= "No Current Stats"%><br>
        <% if @user != current_user %>
            <%= ''%>
        <%else%>
          <%= link_to "Add your current stats", new_user_stat_path(@user, @user.stat), :class => 'myButton' %><br>
        <%end%>
      <%end%>
      <br>
    </div>
    <div class="large-6 columns">
      <%if @user_goals != nil%>
        <h4>Current Goals</h4>
          <%= "Bench Goal: #{ @user_goals.bench }" %><br>
          <%= "Squat Goal: #{ @user_goals.squat }" %><br>
          <%= "Dead lift Goal: #{ @user_goals.dead_lift }" %><br>
          <%= "Goal Mile time: #{ @user_goals.mile }" %><br>
          <% if @user != current_user %>
            <%= ''%><br>
          <%else%>
            <%= link_to "Edit your current goals", new_user_goal_path(@user, @user.goal), :class => 'myButton' %><br>
          <%end%>
        <%else%>
        <%= "No Current Goals"%><br>
          <% if @user != current_user %>
            <%= ''%><br>
          <%else%>
          <%= link_to "Add your current goals", new_user_goal_path(@user, @user.goal), :class => 'myButton' %><br>
        <%end%>
      <%end%>
      <br>
    </div> 
  </div>
</div> 

<div class = 'panel opacity'>
  <div class = 'workout-holder'>
    <% if @user != current_user %>
        <%= ''%><br>
    <%else%>
      <%= link_to "Log a new workout", new_user_workout_session_path(@user), :class => 'myButton' %><br>
    <% end %>
        
    <h4>Workouts Completed</h4>
    <br>
        <div class = 'workouts'>
          <div class = 'row'>
            <ul class="large-block-grid-2 columns">
              <% @user_workout_sessions.each do |session|%>
                <li>
                <table>
                  <%="Date: #{session.date_completed}"%><br>
                  <%="Workout Name: #{session.workout.name}"%><br>
                  <%= link_to "Delete this workout", 'workout_sessions#destroy', method: :delete %>
                  <thead>
                    <tr>
                      <th>Exercise Name</th>
                      <th>Sets</th>
                      <th>Reps</th>
                      <th>Rest Time</th>
                    </tr>
                  </thead>
                  <% session.workout.workout_exercise_connectors.each do |interval| %>
                    <tbody>
                      <tr>
                        <td><%= interval.exercise.name %></td>
                        <td><%= interval.sets %></td>
                        <td><%= interval.reps %></td>
                        <td><%= interval.rest_time %></td>
                      </tr>
                    </tbody>
                  <%end%> 
                </table>
                </li>
              <%end%>  
            </ul>
          </div>
        </div>            
  </div>
  <br>
  <%= link_to "Back to Home", user_path %>
</div>