config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" } do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  root to: "welcomes#index"
  resources :categories
  resources :exercises
  resources :workouts
  resources :friendships
  resources :workout_exercise_connectors
  
  resources :users do
     resources :workout_sessions
     resources :stats
     resources :goals
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :require_login

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def require_login
    unless current_user
      redirect_to new_user_registration_path
    end
  end
end

app/views/categories/index.html.erb
<div class = 'panel margin-top opacity'>

  <h2> Workout Categories </h2>
  <p>Each selected category will list exercises that focus on that area of the body :</p>
  <ul>
    <% @categories.each do |category|%>
      <li><%= link_to "#{category.name}", category_path(category)%></li>
    <% end %>
  </ul>
</div>

app/views/categories/show.html.erb
<div class = 'panel margin-top opacity'>
  <h4><%= @category.name %></h4>
  <p>(Details of exercises and examples coming soon!)
  <ul>
    <% @category.exercises.each do |exercise|  %>
      <li><%= link_to "#{exercise.name}",exercise_path(exercise) %></li>
    <% end %>
  </ul>
  <%= link_to "Back to Categories", categories_path %>
</div>